baseURL = "https://bhanuprakashbhanuri.github.io/"
languageCode = "en-us"
title = "Bhanu Prakash Bhanuri"
theme = "blowfish"
enableRobotsTXT = true

[params]
  author = "Bhanu Prakash Bhanuri"
  description = "Bhanu Prakash Bhanuri — Cloud & Developer. AWS & Python."
  resume = "resume1.pdf"
  profile = "profile.jpg"
  linkedin = "https://www.linkedin.com/in/bhanu-prakash-bhanuri/"
  github = "https://github.com/BhanuPrakashhh3"
  accent = "green"
  showRecent = true







